import { z } from "zod"
import {
  billingCadenceEnum,
  pricingTypeEnum,
  serviceStatusEnum,
  serviceVisibilityEnum,
} from "./types"

export const ServiceSchema = z.object({
  id: z.string(),
  workspaceId: z.string(),
  name: z.string(),
  slug: z.string(),
  tagline: z.string().nullable(),
  description: z.string().nullable(),
  category: z.string().nullable(),
  icon: z.string().nullable(),
  avatar: z.string().nullable(),
  type: z.enum(pricingTypeEnum),
  price: z.number(),
  currency: z.string(),
  interval: z.enum(billingCadenceEnum).nullable(),
  intervalCount: z.int().positive().nullable(),
  turnaroundValue: z.int().positive().nullable(),
  turnaroundUnit: z.string().nullable(),
  isPublishedToStore: z.boolean(),
  status: z.enum(serviceStatusEnum),
  visibility: z.enum(serviceVisibilityEnum),
  featured: z.boolean(),
  sortOrder: z.number().int(),
  autoCreateProject: z.boolean(),
  autoCreateCompany: z.boolean(),
  autoSendBriefForm: z.boolean(),
  autoSendPortalInvite: z.boolean(),
  briefFormId: z.string().nullable(),
  paymentPreferences: z.unknown().nullable(),
  lineItems: z.unknown().nullable(),
  deliverables: z.unknown().nullable(),
  timeline: z.unknown().nullable(),
  paymentSchedule: z.unknown().nullable(),
  legalClauses: z.unknown().nullable(),
  revisionPolicy: z.unknown().nullable(),
  autoApplyRevisionPolicy: z.boolean(),
  autoApplyPaymentSchedule: z.boolean(),
  autoApplyLegalClauses: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
})
